language: php
php:
- 5.4
- 5.5
- 5.6
- hhvm
before_script:
- composer self-update
- composer install --prefer-source --no-interaction --dev
script: phpunit
matrix:
  allow_failures:
  - php: 5.4
  - php: hhvm
  fast_finish: true
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/a849e8f74c53cf95e503
    on_success: change
    on_failure: always
    on_start: false
deploy:
  provider: openshift
  user: jovib29@gmail.com
  password:
    secure: x1Rfx+QHc+1hi+P+wSrGNMTJ7vIsa2AEUEEccxnLUui5KsySH+ObiAAnK23+kart12+psxeZ5QMhbQK548bhnEcCtVOdRCMq6kIDBy+w75pY+az0huN+8koyRV/5ZtqkB5oanikkekM49i6jK4q8os+EPJ/+/FcC4mJ0aFl2n3Q=
  app: phone
  domain: phone-jovibi.rhcloud.com
  on:
    repo: jovib/weph
